### ISSUE TITLE
Deploy on Maven Central Repository

### ISSUE THREAD

**Issue by pmwmedia** [chaudhryfaisal/tinylog2-gelf#1]
Do you have any plans to deploy the artifact on the Maven Central Repository?

**Comment by chaudhryfaisal** [comment]
already available 
```
<dependency>
  <groupId>com.github.chaudhryfaisal</groupId>
  <artifactId>tinylog2-gelf</artifactId>
  <version>0.1.0</version>
</dependency>
````

**Comment by pmwmedia** [comment]
@chaudhryfaisal Unfortunately, the artifact seems to be still unavailable in the  Maven Central Repository.

According to maven.org ist is missing: https://search.maven.org/artifact/com.github.chaudhryfaisal/tinylog2-gelf

However, your other artifacts are there: https://search.maven.org/search?q=g:com.github.chaudhryfaisal
